import type {BOOLEAN, BOOLEAN_OPERATION, CANVAS, COMPONENT, COMPONENT_SET, DOCUMENT, ELLIPSE, FRAME, GROUP, INSTANCE, LINE, RECTANGLE, REGULAR_POLYGON, SLICE, STAR, TEXT, VECTOR} from "figma-api";

export type NodeType =
  | DOCUMENT
  | CANVAS
  | FRAME
  | GROUP
  | VECTOR
  | BOOLEAN
  | BOOLEAN_OPERATION
  | STAR
  | LINE
  | ELLIPSE
  | REGULAR_POLYGON
  | RECTANGLE
  | TEXT
  | SLICE
  | COMPONENT
  | COMPONENT_SET
  | INSTANCE;
